### ISSUE TITLE
--dump one check has two printed times?

### ISSUE THREAD

**Issue by PlexSheep** [PlexSheep/netpulse#42]
```
103988:
        Time: 2024-11-28 16:57:00 +01:00
        Time: 2024-11-09 02:05:01 +01:00
        Type: HTTP(S)
        Ok: true
        Target: 2606:4700:4700::1111
        Latency: 49 ms
        Hash: c41d3ec352746649d54ac64fbeb0ba24bbb9532f65ae6ef900f365e268f630b7
```
